### ISSUE TITLE
Why are we using buffer's?

### ISSUE THREAD

**Issue by PullJosh** [ScratchAgarioBots/agario-bot#44]
Why draw a line of the point at which we should stay away? Instead, wouldn't it make more sense to have "gradients" - further away is better, but not necessary?

**Comment by matthewr6** [comment]
Yes

**Comment by PullJosh** [comment]
I'll work on it. This could be a big commit. :P

**Comment by an-OK-squirrel** [comment]
Okay.

**Comment by PullJosh** [comment]
Either I just wrote some epic code, or I just got really lucky.
Score:702

**Comment by matthewr6** [comment]
wow
we need videos
I think you're just really lucky - I used the same code as you had for the 1k and only got about .1k :P

**Comment by PullJosh** [comment]
xD I know.

**Comment by PullJosh** [comment]
It's some new code I just wrote, though, which gives me hope.

But the code makes no sense (it _shouldn't_ work), which concerns me.

**Comment by PullJosh** [comment]
... Turns out I just got lucky.

**Comment by heyseth** [comment]
:(

**Comment by PullJosh** [comment]
Good news, though. I think I know how to make it actually good.

**Comment by matthewr6** [comment]
coding logic:
code that should work doesn't
code that shouldn't work does

**Comment by heyseth** [comment]
More good news, I fixed the problem with Chrome and now skins and names are disabled by default :)

**Comment by PullJosh** [comment]
Yay! :D

**Comment by an-OK-squirrel** [comment]
more realistic coding logic:
nothing ever works

**Comment by an-OK-squirrel** [comment]
Why skins? I love skins.

**Comment by an-OK-squirrel** [comment]
Also: Gradients are good, but you should still have a small-ish buffer, if it comes to the point that it gets really close to an enemy because of something else..

**Comment by heyseth** [comment]
The skins are disabled by default because we're gonna be sharing this on Scratch, and some Scratch users might be offended by some if the skins (such as [this](http://agarioskins.com/skin.php?n=nazi) one and [this](http://agarioskins.com/skin.php?n=satanist) one)

**Comment by an-OK-squirrel** [comment]
Oh, i see. Never seen those two.

**Comment by an-OK-squirrel** [comment]
Also, anyone here have a youtube channel?

**Comment by heyseth** [comment]
PullJosh [does](https://www.youtube.com/channel/UCyzmitdHlr_WnDifP9b_YhA/videos)

**Comment by an-OK-squirrel** [comment]
PJ, can you upload a video of this?

**Comment by PullJosh** [comment]
1) The gradients will be at 100% value before the center of the enemy. Kind of like this:
![image](https://cloud.githubusercontent.com/assets/5458180/8438882/88947644-1f36-11e5-8645-8efe62b911e6.png)

2) Already did. https://www.youtube.com/watch?v=PH57efMvKVA

**Comment by heyseth** [comment]
He has

**Comment by heyseth** [comment]
Ninja'd by half a second!

**Comment by PullJosh** [comment]
:P

**Comment by PullJosh** [comment]
Once the bot gets better (ready to be released), I'll embed the vid in the "about section" of the bot's website.

**Comment by PullJosh** [comment]
(But with a new, updated vid, of course.)

**Comment by an-OK-squirrel** [comment]
oh, i have to take off my safety mode

**Comment by an-OK-squirrel** [comment]
man, if you had names on it'd probably be on the leaderboard

**Comment by PullJosh** [comment]
I checked at one point in the vid, and it wasn't. (Had to censor one of the names... quite boring.)

**Comment by an-OK-squirrel** [comment]
Sorry for that. Anyways, can you help me on #43 now?

**Comment by PullJosh** [comment]
My code is getting there...

**Comment by an-OK-squirrel** [comment]
Cool.

**Comment by an-OK-squirrel** [comment]
I'll wait for you to be done before I start making the results thing

**Comment by PullJosh** [comment]
You might be waiting a while. xD

Although it's getting there, it still has a long ways to go.

**Comment by an-OK-squirrel** [comment]
I" think i can get it done without conflicts... It's for results.

**Comment by an-OK-squirrel** [comment]
I know this is totally unrelated, but...
![git can t take a compliment](https://cloud.githubusercontent.com/assets/12722625/8439754/97694508-1f33-11e5-8ff0-2c5873a02a76.png)
Git just can't take a compliment.

**Comment by matthewr6** [comment]
powershell?
wow.

**Comment by an-OK-squirrel** [comment]
Yeah, powershell. I only use it for git so...

**Comment by matthewr6** [comment]
Search for Cmder

**Comment by an-OK-squirrel** [comment]
Nah.

**Comment by heyseth** [comment]
I use git bash for git

**Comment by an-OK-squirrel** [comment]
Wow, that would make sense!

**Comment by PullJosh** [comment]
Coming quite close to a quality solution... It turns out I didn't have to write that much new code, it just took a while to figure out. Expect commits to [bufferless](https://github.com/ScratchAgarioBots/agario-bot/tree/bufferless) soon!

**Comment by an-OK-squirrel** [comment]
KK!

**Comment by PullJosh** [comment]
Got a working demo here: adb9fbbc9d0340759e5b28ebb8a9c8164e3760ac

It's certainly not perfect, but here are a few of the differences:

PROS:
1) Bug where AI attempts to get food that is within enemy buffers is less of an issue (though still worth fixing at some point)
2) Less likely to die, especially after initial 100 points or so (first stretch has to get a bit lucky, but once you get past about 100, it's far better at staying alive)
3) Less likely to get into [bad situations](https://github.com/ScratchAgarioBots/agario-bot/issues/22).
4) Does a better job of going after smaller players (while still staying safe)

CONS:
1) As already stated, no better (possibly worse) during initial stages.
2) Much more likely to get stuck in corner.
3) #23 will be much harder to do.

**Comment by an-OK-squirrel** [comment]
Will check out tommorow. On mobile

**Comment by an-OK-squirrel** [comment]
How about buffers for <100?

**Comment by matthewr6** [comment]
Good idea

**Comment by an-OK-squirrel** [comment]
I 'm good with those :P

**Comment by PullJosh** [comment]
xD Feel free to push directly to the bufferless branch.

**Comment by an-OK-squirrel** [comment]
Kk

**Comment by matthewr6** [comment]
not anymore, sorry
will restore it

**Comment by an-OK-squirrel** [comment]
It's  fine

**Comment by matthewr6** [comment]
someone take a look at my pull request

**Comment by an-OK-squirrel** [comment]
I did.

**Comment by an-OK-squirrel** [comment]
#49?

**Comment by matthewr6** [comment]
Yeah, merge it if it's good

**Comment by an-OK-squirrel** [comment]
Checkin it now...
